### ISSUE TITLE
jaer git init not working in linux because of .exe file

### ISSUE THREAD

**Issue by tobidelbruck** [SensorsINI/jaer#39]
Get this exception in linux ubuntu 18.04, cause unknown:

index.lock, create new FileSnapshot: lastRead=2021-03-28 09:01:29.206000000, lastModified=2021-03-28 09:01:29.000000000, size=262232, fileKey=(dev=10306,ino=1186381)
09:01:29.206 [Thread-16] DEBUG o.e.j.i.storage.file.FileSnapshot - file=jaer-clone/.git/index, create new FileSnapshot: lastRead=2021-03-28 09:01:29.206000000, lastModified=2021-03-28 09:01:29.000000000, size=262232, fileKey=(dev=10306,ino=1186381)
Mar 28, 2021 9:01:29 AM net.sf.jaer.JaerUpdater lambda$null$6
INFO: cloned Git[Repository[jaer-clone/.git]]
09:01:29.229 [Thread-16] DEBUG org.eclipse.jgit.lib.Repository - close() called when useCnt is already zero for Repository[jaer-clone/.git]
java.lang.IllegalStateException: null
	at org.eclipse.jgit.lib.Repository.close(Repository.java:948)
	at org.eclipse.jgit.api.Git.close(Git.java:132)
	at net.sf.jaer.JaerUpdater.lambda$null$6(JaerUpdater.java:430)
	at java.lang.Thread.run(Thread.java:745)
Mar 28, 2021 9:01:29 AM net.sf.jaer.JaerUpdater lambda$null$6
INFO: copying non-existing files to release
Mar 28, 2021 9:01:30 AM net.sf.jaer.JaerUpdater$3 doInBackground
WARNING: java.nio.file.NoSuchFileException: jAERViewer_win64.exe

**Comment by tobidelbruck** [comment]
not a problem now
