### ISSUE TITLE
When I opened jAERViewer_win64.exe, it occured these errors. why? I have installed jdk 1.8.

### ISSUE THREAD

**Issue by LI474525323** [SensorsINI/jaer#45]
![image](https://user-images.githubusercontent.com/55075770/200831467-dfc3bb53-c6aa-4feb-8229-3b3ad5e21c24.png)
java.lang.ClassNotFoundException: net.sf.jaer.JAERViewer
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:77)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)

**Comment by julio-guillen** [comment]
Hi,

This is a weird one. JVM says that he is not finding  the class "net.sf.jaer.JAERViewer" when trying to launch jAER. I think you should provide more info in order to understand better the situation.

Regards

**Comment by tobidelbruck** [comment]
Please try the install4j insttaller. It comes bundled with Java and all the libraries and can be converted to .git working copy from the Help menu.
