### ISSUE TITLE
java.lang.ClassNotFoundException: net.sf.jaer.JAERViewer

### ISSUE THREAD

**Issue by WXiuCheng** [SensorsINI/jaer#50]
java.lang.ClassNotFoundException: net.sf.jaer.JAERViewer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)

**Comment by tobidelbruck** [comment]
any update on this?

**Comment by tobidelbruck** [comment]
inactivity
